// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task12_EraaSoft.DataAccess;

#nullable disable

namespace Task12_EraaSoft.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609185644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task12_EraaSoft.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationID")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("SpecializationID");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Img = "doctor1.jpg",
                            Name = "Dr. John Smith",
                            SpecializationID = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            Img = "doctor2.jpg",
                            Name = "Dr. Sarah Johnson",
                            SpecializationID = 2
                        },
                        new
                        {
                            DoctorId = 3,
                            Img = "doctor4.jpg",
                            Name = "Dr. Emily Davis",
                            SpecializationID = 3
                        },
                        new
                        {
                            DoctorId = 4,
                            Img = "doctor3.jpg",
                            Name = "Dr. Michael Lee",
                            SpecializationID = 4
                        },
                        new
                        {
                            DoctorId = 5,
                            Img = "doctor5.jpg",
                            Name = "Dr. William Clark",
                            SpecializationID = 5
                        });
                });

            modelBuilder.Entity("Task12_EraaSoft.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("DoctorId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Task12_EraaSoft.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializationID");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationID = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            SpecializationID = 2,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            SpecializationID = 3,
                            Name = "Dermatology"
                        },
                        new
                        {
                            SpecializationID = 4,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            SpecializationID = 5,
                            Name = "Neurology"
                        });
                });

            modelBuilder.Entity("Task12_EraaSoft.Models.Doctor", b =>
                {
                    b.HasOne("Task12_EraaSoft.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Task12_EraaSoft.Models.Enrollment", b =>
                {
                    b.HasOne("Task12_EraaSoft.Models.Doctor", "Doctor")
                        .WithMany("Enrollments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Task12_EraaSoft.Models.Doctor", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Task12_EraaSoft.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
